// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzT9yiwL7YqAG-bgm1bGofeBSrUEkHs1I',
    appId: '1:876113322408:web:ca919f100cd296f1263d9d',
    messagingSenderId: '876113322408',
    projectId: 'backendgabaritoplus',
    authDomain: 'backendgabaritoplus.firebaseapp.com',
    storageBucket: 'backendgabaritoplus.firebasestorage.app',
    measurementId: 'G-EX72HRPF0W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVl5J4-EZSqNPw2_xRXUon8hHmYJfBW6k',
    appId: '1:876113322408:android:bd8751c36cbabedf263d9d',
    messagingSenderId: '876113322408',
    projectId: 'backendgabaritoplus',
    storageBucket: 'backendgabaritoplus.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTlMLvtCYVz9TbveBk5SVEaguLLVtq_c8',
    appId: '1:876113322408:ios:1f9de0abab54024b263d9d',
    messagingSenderId: '876113322408',
    projectId: 'backendgabaritoplus',
    storageBucket: 'backendgabaritoplus.firebasestorage.app',
    iosBundleId: 'com.example.gabaritoPlus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTlMLvtCYVz9TbveBk5SVEaguLLVtq_c8',
    appId: '1:876113322408:ios:1f9de0abab54024b263d9d',
    messagingSenderId: '876113322408',
    projectId: 'backendgabaritoplus',
    storageBucket: 'backendgabaritoplus.firebasestorage.app',
    iosBundleId: 'com.example.gabaritoPlus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzT9yiwL7YqAG-bgm1bGofeBSrUEkHs1I',
    appId: '1:876113322408:web:199438234e619753263d9d',
    messagingSenderId: '876113322408',
    projectId: 'backendgabaritoplus',
    authDomain: 'backendgabaritoplus.firebaseapp.com',
    storageBucket: 'backendgabaritoplus.firebasestorage.app',
    measurementId: 'G-J23QZG04V7',
  );
}
